### ISSUE TITLE
安装了好几次，刷新主机有问题

### ISSUE THREAD

**Issue by wysl** [qitan/SOMS#2]
系统版本：centos 7.3    python 使用系统默认安装的 版本2.7.5    
yum 安装 c++ 修改为   gcc-c++
yum -y update && yum -y install mariadb mariadb-devel mariadb-server wget epel-release python-devel gcc gcc-c++ make openssl openssl-devel passwd libffi libffi-devel
后按照流程安装完
python manage.py runserver 0.0.0.0:8080后进入主机管理刷新，页面报如下错

HTTPError at /deploy/key_list_import/
HTTP Error 401: Unauthorized
Request Method:	GET
Request URL:	http://192.168.91.150:8080/deploy/key_list_import/
Django Version:	1.9
Exception Type:	HTTPError
Exception Value:	
HTTP Error 401: Unauthorized
Exception Location:	/usr/lib64/python2.7/urllib2.py in http_error_default, line 558
Python Executable:	/usr/bin/python
Python Version:	2.7.5
Python Path:	
['/data/wwwroot/SOMS',
 '/usr/lib64/python27.zip',
 '/usr/lib64/python2.7',
 '/usr/lib64/python2.7/plat-linux2',
 '/usr/lib64/python2.7/lib-tk',
 '/usr/lib64/python2.7/lib-old',
 '/usr/lib64/python2.7/lib-dynload',
 '/usr/lib64/python2.7/site-packages',
 '/usr/lib64/python2.7/site-packages/gtk-2.0',
 '/usr/lib/python2.7/site-packages']

**Comment by qitan** [comment]
HTTP Error 401: Unauthorized

修改settings_local.py相关账号密码
