### ISSUE TITLE
刷新资产信息获取磁盘信息报错TypeError: int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by cybernagle** [qitan/SOMS#4]
TypeError: int() argument must be a string or a number, not 'NoneType'
刷新资产信息过程中,在获取disk.usage过程中如果磁盘空间为None,会抛出异常进而无法导入.
因为windows磁盘有可能会是CD-ROM,无存储空间.
添加一个判断后,恢复.

**Comment by qitan** [comment]
设计时并无打算兼容win。。。
