### ISSUE TITLE
python 2.7 SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by cybernagle** [qitan/SOMS#5]
python2.7版本当中,urllib2在发起urlopen请求过程中,发生SSL: CERTIFICATE_VERIFY_FAILED错误.

**Comment by qitan** [comment]
python 升级到 2.7.9 之后引入了一个新特性，当使用urllib.urlopen打开一个 https 链接时，会验证一次 SSL 证书。
也就是说我们部署的网站使用了自签名的证书时就会抛出一个错误
可以查看我的博客

**Comment by cybernagle** [comment]
thanks
